/**
 * The names of the sounds that come with the tool.
 *
 * A sound is identified by its path, which says nothing about the sound.
 * Only the file name is held here; the name shown lives with the translations.
 */
const PRESET_SOUND_FILES: ReadonlySet<string> = new Set([
  'alarm',
  'barrier',
  'bash-finish',
  'bash-large',
  'bash-medium',
  'bash-small',
  'beam-small',
  'book-stack1',
  'bow-pierce',
  'bow-release',
  'breath-fire',
  'breath-ice',
  'breath-poison',
  'breath-wind',
  'buff',
  'card-open1',
  'card-turn-over1',
  'charge',
  'cleanse',
  'cointoss',
  'collapse',
  'cure-large',
  'cure-medium',
  'cure-small',
  'damage-large',
  'damage-medium',
  'damage-small',
  'dark',
  'drain',
  'earth-upheaval',
  'explosion-huge',
  'explosion-large',
  'explosion-small',
  'fire-large',
  'fire-medium',
  'fire-small',
  'flash-impact',
  'gravity',
  'gravity-large',
  'gun-handgun',
  'gun-machinegun',
  'gun-rifle',
  'gun-smg',
  'heal-large',
  'heal-medium',
  'heal-small',
  'holy',
  'holy-blade',
  'ice-large',
  'ice-medium',
  'ice-small',
  'laser-hit',
  'laserbeam',
  'lasergun',
  'mech-damage-large',
  'mech-damage-medium',
  'mech-damage-small',
  'mech-heal-large',
  'mech-heal-medium',
  'mech-heal-small',
  'missile-launch',
  'poison',
  'qigong',
  'reflect',
  'rock-break',
  'rocket-launch',
  'shoulder-touch1',
  'slash-charged',
  'slash-combo',
  'slash-iai',
  'slash-large',
  'slash-small',
  'spo_ge_saikoro_teburu01',
  'spo_ge_saikoro_teburu02',
  'status-bind',
  'status-cure',
  'status-curse',
  'status-petrify',
  'status-sleep',
  'stone-hit',
  'summon',
  'super-arts',
  'thunder-bolt',
  'thunder-large',
  'thunder-small',
  'tm2_pon002',
  'tm2_swing003',
  'tm2_switch001',
  'warp',
  'wind-large',
  'wind-small',
]);

/** The file name, without its directory or its extension. */
export function soundFileName(identifier: string): string {
  const file = identifier.split('/').pop() ?? identifier;
  return file.replace(/\.(mp3|wav|ogg|m4a)$/i, '');
}

/** The translation key of the name. Empty for a sound that was brought in. */
export function presetSoundLabelKey(identifier: string): string {
  const name = soundFileName(identifier);
  return PRESET_SOUND_FILES.has(name) ? `feature.effect.sounds.${name}` : '';
}
